### ISSUE TITLE
RFE: allow to use multiple commit types per changelog section

### ISSUE THREAD

**Issue by McFoggy** [qoomon/git-conventional-commits#148]
Would you be open to a change that would allow to group several commit types inside a changelog section, configuration could be something like:

````
  headlines:
    feat: Features
    "fix,style": Enhancements
    perf: Performance Improvements
    "ci,build,ops": CI/CD
    "chore,docs": Misc
    breakingChange: BREAKING CHANGES
````

Note that such a change is backward compatible with what exists today.

**Comment by qoomon** [comment]
I think the easiest solution would be to set the same headline for the types and group by headlines, this way you get an syntax error in yaml if you define a value twice.

Example
```yaml
headlines:
    feat:  Features
    fix:   Enhancements
    style: Enhancements
    perf:  Performance Improvements
    ci:    CI/CD
    build: CI/CD
    ops:   CI/CD
    chore: Misc
    docs:  Misc
    breakingChange: BREAKING CHANGES
```

Because it is an edge case, the redundancy is okay in my opinion.
WDYT?

**Comment by qoomon** [comment]
Or I could add a new `sections` field e.g.
```yaml
sections:
   Features: [feat]
   Enhancements: [fix, style]
   Performance Improvements: [perf]
   CI/CD: [ci, build, ops]
   Misc: [chore, docs]
   BREAKING CHANGES: [breakingChange]
```

**Comment by qoomon** [comment]
The new approach could also replace the `commitTypes`list
before
```yaml
changelog:
 commitTypes:
  - feat
  - fix
  - perf
  - merge
  headlines:
    feat: Features
    fix: Bug Fixes
    perf: Performance Improvements
    merge: Merges
    breakingChange: BREAKING CHANGES
```

```yaml
changelog:
 sections:
   Features: [feat]
   Bug Fixes: [fix]
   Performance Improvements: [perf]
   Merges: [merge]
   BREAKING CHANGES: [breakingChange]
```

WDYT?
